### ISSUE TITLE
install steps for ubuntu and libreoffice

### ISSUE THREAD

**Issue by tony1223** [HugoHasenbein/redmine_more_previews#6]
I have installed this on ubuntu 20.04 headless server for docx/xlsx.
the following install steps:
 sudo apt install default-jre
 sudo apt install libreoffice-java-common
 sudo apt install libreoffice-core
 sudo apt install libreoffice-writer
 sudo apt install libreoffice-wcalc
 sudo apt install libreoffice-impress

You should test the setting for soffice before install the plugins, the test command is
 soffice --headless --convert-to html <the_file_you_want_to_preview>

**Comment by waikin714** [comment]
thanks you! I work too.

My Environment: docker redmine:4.1.1
my step:
step 1: libreoffice
1.1. download libreoffice
`apt-get update && apt-get install -y --force-yes libreoffice`
it will show some errors, but in the end it work.
1.2 make suer soffice is installed 
  `which soffice`
1.3 test soffice 
  `soffice --headless --convert-to html <the_file_you_want_to_preview>`
   it will product html file in the working directory.

step 2: redmine more previews
2.1 download this repository
2.2 rename folder name from 'redmine_more_previews-main' to 'redmine_more_previews'
2.3 make sure the folder structure of 'redmine_more_previews' is as below:
redmine_more_previews
    ├─.github
    │  └─workflows
    ├─app
    │  └─views
    ├─assets
    │  └─images
    ├─config
    │  └─locales
    ├─converters
    ├─...
2.4 put 'redmine_more_previews' folder to /usr/src/redmine/plugins
2.5 delete folder redmine_more_previews\converters\zippy\ 
because this cause bundle install error in my environment, and I don't need zippy.
zippy is use to lets you preview zip, tgz or tar-Files in the browser
2.6 go to redmine root folder and type `bundle install`
2.7 restart if need, my environment seems don't need
2.8  Go to redmine website -> Administration -> Plugins -> Redmine More Previews Configuration
Choose the following options
* use embed-tag or iframe-tag
* cache previews (speeds views, may bloat your rails root's tmp folder a bit)
* activate sub plugins above
* for each sub plugin activate the file extension for files you want to preview (if you choose two sub plugins converting the same file type, then a warning will be issued and the last activated sub plugin will do the conversion).
