### ISSUE TITLE
plugin is installed, but nothing happen

### ISSUE THREAD

**Issue by grefabu** [HugoHasenbein/redmine_more_previews#94]
Hi,

I was able to install the plugin to an redmine 5.0.4 on an debian12.

I could configure the plugin, but it seem nothing happen.
When I upload an file (pdf or docx) I still could only download the files,...

Thank you for ideas

Gregor

p.s. I'm rather new on redmin already now, so I'm happy to bring up redmine, migrate the old data and activate this plugin ;-)

**Comment by HugoHasenbein** [comment]
Dear User,

you may have to activate the plugin for your project. This was implemented due to user demand and I think it makes sense.

Go to "Projects" Select your project, Select the "Settings"-tab , then select the "information"-tab. There, on the bottom activate "Redmine More Previews".

Further, you may have to activate, which previews you want to see under "Administration" (as admin user) -> "Plugins" -> "Redmine More Previews". There activate the previewers together with the file types you want to convert. You may select all. It is good practice to only select those you want to see.

best wishes and enjoy

Stephan

**Comment by grefabu** [comment]
Hi,

sorry, I found the solution bye study the closed issues.
I dind't close this issue instantly, but I do it now,...

Thank You for reply!

Gregor
